Adding image onFocus and allowing image container style props for DynamicCollage
aspect-apps/react-native-images-collage pull request #21
Opened 2021-02-09 17:24 UTC by harbolaez

Adding `onImageFocus` and `imageFocussedStyle` prop to DynamicCollage. When a user pressed on a image it will trigger the onImafeFocus property exposing two parameters metrixId and imageIndex. You can add custom style to the focussed image with the prop `imageFocussedStyle`

## API

```
<DynamicCollage
  images={[]}
  onImageFocus={(m, i) => {
    console.log(m,i)
  }}
  imageFocussedStyle={{ borderColor: "red" }}
  ...
/>
```

2021-02-09 19:45 UTC, harbolaez commented
@lukebrandonfarrell let me know what you think? But looking at this and thinking about it again, I think it makes sense to have a `imageOnPress` callback too which lets the user set the style of that corresponding image or anything they want to do. Also maybe exposing the location of where the press was trigger might be worth it too. let me know what you think?

2021-02-10 08:22 UTC, lukebrandonfarrell commented
Thanks for the PR @harbolaez ! Will test these changes this evening, then will merge and push if I discover no issues :)

2021-02-10 11:28 UTC, lukebrandonfarrell requested changes
Nice work on this PR! This functionality was actually quite complex as you had to track the selected ID of the image. Here are my review comments:

I propose that instead of wrapping with a touchable we handle the click inside `onPanResponderEnd` i.e. like below (I tested this):

```js
 onPanResponderEnd: (e, gestureState) => {
       // Focusses the image, if user just taps it, and there is no movement or holding
        if(Math.abs(gestureState.dx) < 5 && !this.state.selected) {
          if(this.props.onImageFocus) this.props.onImageFocus();
        }
         // Disable scaling, and panning
        this.panning = false;
        this.scaling = false;
       ...
```

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/CollageImage.js
> +      },
I propose we keep this as it was and handle the tap in `onPanResponderEnd`

```suggestion
      onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,
```

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/CollageImage.js
> +          <TouchableWithoutFeedback onPress={this.props.onImageFocus}>
Not needed anymore if we add the handling in `onPanResponderEnd`
```suggestion
```

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/CollageImage.js
> +          </TouchableWithoutFeedback>
```suggestion
```

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  onImagePress: PropTypes.func,
Is there any need for this? Can't find it being used
```suggestion
```

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  onImageFocus: PropTypes.func,
Could we also add `imageContainerStyle` and `imageFocussedStyle` here to the PropTypes?

And also if possible update the documentation README.md with their usage?

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  },
What was the reason behind this? Can't seem to figure it out

2021-02-10 11:28 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  }
A few things for this:

- Could we add a JSDoc comment explaining something about what this function is used for and the param types (good for IDE intelligence)
- What is the reason for wrapping this in a `function` with bind and returning it? Instead could we do:

```
 onImageFocus={() => this.setImageFocusId(m, i)}
...
setImageFocusId(m, i) {
    const imageId = `image${m}-${i}`;
    this.setState((prevState) => ({
      imageFocusId: prevState.imageFocusId === imageId ? null : imageId,
    }));

    this.props.onImageFocus && this.props.onImageFocus({ m, i });
}
```
The above is a bit easier to read and follow

2021-02-10 15:22 UTC, harbolaez commented on src/DynamicCollage.js
> +  },
Yeah - this was to allow end-user to add their custom border to the image container while keeping the default as you had before.

2021-02-10 16:19 UTC, harbolaez commented on src/DynamicCollage.js
> +  }
Yeah that removing the touchable would do it. I wanted to expose the `event` on where the press happens, just incase we wanted to show a tooltip, etc. But that' fine for now.

2021-02-11 11:47 UTC, lukebrandonfarrell commented
@harbolaez Will review this today :)

2021-02-12 17:25 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  }
Makes sense! Do you think we can update this block to this? It's more readable and inline with the other callback functions.

```
onImageFocus={(event) => this.setImageFocusId(event, m, i)}

...

setImageFocusId(event, m, i) {
    const imageId = `image${m}-${i}`;
    this.setState((prevState) => ({
      imageFocusId: prevState.imageFocusId === imageId ? null : imageId,
    }));

    this.props.onImageFocus && this.props.onImageFocus(event, m, i);
}
```

2021-02-12 17:25 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  },
Sounds good!

2021-02-12 17:26 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +  }
After that, this looks good to me!

2021-02-12 19:12 UTC, lukebrandonfarrell commented
@harbolaez if you could also resolve the conflicts, that would be great! Then I'll create a new version on NPM for all three of these features #21 #22 and #20

2021-02-12 19:13 UTC, lukebrandonfarrell commented
@all-contributors please add @harbolaez for code and documentation

2021-02-18 11:14 UTC, lukebrandonfarrell approved these changes
Looks good to me! 💯 

Just need to run a local test then will publish this! 👍

2021-02-18 11:14 UTC, lukebrandonfarrell commented on src/DynamicCollage.js
> +      imageFocusId: "",
```suggestion
      imageFocusId: null,
```

2021-02-18 11:14 UTC, lukebrandonfarrell commented on README.md
> +| imageContainerStyle  | object   | Yes      | style    | Style applied to the image container of the collage.                                                                      |
```suggestion
| imageContainerStyle  | object   | Yes      | style    | Style applied to each image container.                                                                      |
```

2021-02-18 11:14 UTC, lukebrandonfarrell commented on README.md
> +| imageFocussedStyle   | object   | Yes      | style    | Style applied to the focused image container of the collage.                                                              |
```suggestion
| imageFocussedStyle   | object   | Yes      | style    | Style applied to the focused image container.                                                              |
```

2021-02-18 11:15 UTC, merged